-- NMRCYHUB Custom WindUI Loader (Dynamic Module Loader)
-- This script dynamically requires and executes modules from GitHub on the fly.
-- No build/bundling step is required!

local repoBaseUrl = "https://raw.githubusercontent.com/NMRCYHUB/ui/main/main/windui-src/"
local cache = {}

-- Utility to resolve path traversal (relative paths like . and ..)
local function resolvePath(basePath, relativePath)
    relativePath = relativePath:gsub("\\", "/")
    if relativePath:sub(1, 2) == "./" then
        relativePath = relativePath:sub(3)
    end
    
    local baseParts = {}
    for part in basePath:gmatch("[^/]+") do
        table.insert(baseParts, part)
    end
    
    local relParts = {}
    for part in relativePath:gmatch("[^/]+") do
        table.insert(relParts, part)
    end
    
    for _, part in ipairs(relParts) do
        if part == ".." then
            if #baseParts > 0 then
                table.remove(baseParts)
            end
        elseif part ~= "." then
            table.insert(baseParts, part)
        end
    end
    
    return table.concat(baseParts, "/")
end

-- Dynamic Require implementation
local function customRequire(path, currentDir)
    -- Intercept build/package require since it is generated by workflows
    if path == "../build/package" or path == "build/package" then
        return '{"version": "1.6.65", "name": "windui"}'
    end
    
    local absolutePath = resolvePath(currentDir, path)
    if not absolutePath:match("%.lua$") then
        absolutePath = absolutePath .. ".lua"
    end
    
    if cache[absolutePath] then
        return cache[absolutePath]
    end
    
    local url = repoBaseUrl .. absolutePath
    local success, content = pcall(game.HttpGet, game, url)
    if not success or not content or content == "404: Not Found" then
        -- Fallback: Check if it's a folder require (looks for /Init.lua inside it)
        local folderInitPath = absolutePath:gsub("%.lua$", "/Init.lua")
        url = repoBaseUrl .. folderInitPath
        success, content = pcall(game.HttpGet, game, url)
        if success and content and content ~= "404: Not Found" then
            absolutePath = folderInitPath
        else
            error("[WindUI Loader] Failed to load module: " .. path .. " (resolved as " .. absolutePath .. ") from URL: " .. url)
        end
    end
    
    -- Extract directory part of the path for next requires
    local newCurrentDir = ""
    local parts = {}
    for part in absolutePath:gmatch("[^/]+") do
        table.insert(parts, part)
    end
    if #parts > 1 then
        table.remove(parts)
        newCurrentDir = table.concat(parts, "/") .. "/"
    end
    
    local func, err = loadstring(content, "=" .. absolutePath)
    if not func then
        error("[WindUI Loader] Syntax error in module " .. absolutePath .. ": " .. tostring(err))
    end
    
    local env = setmetatable({
        require = function(targetPath)
            return customRequire(targetPath, newCurrentDir)
        end
    }, { __index = getfenv(0) })
    
    setfenv(func, env)
    
    local moduleResult = func()
    cache[absolutePath] = moduleResult
    return moduleResult
end

return customRequire("Init.lua", "")
